### ISSUE TITLE
Is it possible to print the intersection elements?

### ISSUE THREAD

**Issue by yanzifan021** [osu-crypto/libPSI#14]
I have compiled and run the frontend.exe iwth kkrt successfully. I tried to supply two csv files to compute the intersection. However, the output file doesn't contain the intersected element but some numbers.
I am running the frontend.exe using
 ```./bin/frontend.exe -kkrt -r 1 -in bob.csv -v```
 ```./bin/frontend.exe -kkrt -r 1 -in alice.csv -v```

the input files look like this
```
aaa
bbb
ccc
ddd
eee
```
the output file looks like this: (I think this stands for the intersection size?)
```
2
1
0
3
4
```
Is it possible to print the intersection elements?
Thanks in advance!

**Comment by ladnir** [comment]
There is no command line switch to do this. However, that's a trivial modification to the code. Change the following to output set[i] instead of just i. 

https://github.com/osu-crypto/libPSI/blob/100e0749b1a9be03534e97f8c388cf9ba8fba264/frontend/fileBasedPSI.cpp#L153

**Comment by yanzifan021** [comment]
> There is no command line switch to do this. However, that's a trivial modification to the code. Change the following to output set[i] instead of just i.
> 
> https://github.com/osu-crypto/libPSI/blob/100e0749b1a9be03534e97f8c388cf9ba8fba264/frontend/fileBasedPSI.cpp#L153

Thanks for the quick reply!
I tried to change ```i``` to ```set[i]```, but it said set is not defined, so i guess what you mean is intersection?
I have changed line 153 to  ````file << intersection[i] << "\n";```
But it still gives me integers instead of strings.
```
output:
0
1
2
3
4
```
Does the set mean the lines parsed from the original files?
Thanks

**Comment by ladnir** [comment]
when I said `set` I was referring to the original set that you use as input. This is currently not a parameter of that function. You would have to add it. The `std::vector<u64> intersection` parameter is a list of the indices of the items in the intersection. So that output `2 1 0 ...` means that the 2nd set item, 1st set item, 0th set item, ... are all in the intersection. 

So to get your desired functionality, you need to add `set` as a parameter to this function call 

https://github.com/osu-crypto/libPSI/blob/100e0749b1a9be03534e97f8c388cf9ba8fba264/frontend/fileBasedPSI.cpp#L249

and then do what I said above.

**Comment by yanzifan021** [comment]
> when I said `set` I was referring to the original set that you use as input. This is currently not a parameter of that function. You would have to add it. The `std::vector<u64> intersection` parameter is a list of the indices of the items in the intersection. So that output `2 1 0 ...` means that the 2nd set item, 1st set item, 0th set item, ... are all in the intersection.
> 
> So to get your desired functionality, you need to add `set` as a parameter to this function call
> 
> https://github.com/osu-crypto/libPSI/blob/100e0749b1a9be03534e97f8c388cf9ba8fba264/frontend/fileBasedPSI.cpp#L249
> 
> and then do what I said above.

Thank you!
