### ISSUE TITLE
how to make both parties get intersection?

### ISSUE THREAD

**Issue by heybrooo** [osu-crypto/libPSI#16]
hello, Is there a way to make  both parties to get the intersection result in KKRT16 ？

**Comment by ladnir** [comment]
the party that learns the intersection should send it to the other.

**Comment by heybrooo** [comment]
thank you for your replyment

**Comment by heybrooo** [comment]
Is this determined by the property of OT？

**Comment by ladnir** [comment]
The protocol has a "Sender" and "Receiver". The library haas classes with these names. The Receiver learns the intersection. The sender learns nothing.

If you want the sender to learn it, then have the party that runs the PSI Reciever send the intersection to the other party.

**Comment by MetaOD** [comment]
@ladnir Thank you for the clarification; just one question, can the Sender (I would assume `sender` denote the party who sends out the query) learns the intersection, instead of the Receiver?

Overall, I am wondering if one-way PSI, like kkrt, can offer what PSM states to offer (https://github.com/google/private-membership)? 

Thank you very much!

**Comment by ladnir** [comment]
The receiver receives the output. That's what it means to be the receiver. Idk about what Google does.
