### ISSUE TITLE
One question for kkrt: what happens if the same secret key is used to calculate the OPRF

### ISSUE THREAD

**Issue by Shareong** [osu-crypto/libPSI#40]
As mentioned in the paper, both parties compute the mapping of inputs to buckets based on the same cuckoo hash, and then perform `1.2n + s`  times OPRF (Don't consider OTE) with different random numbers corresponding to hash buckets. 

I envisioned an optimization method:  if only one random number is used, one party uses this random number to execute `n` times PRF, and both parties perform `n` times OPRF with the same random number. **In this way, there is no need to calculate the cuckoo hash**, and the number of OPRF calculations is also reduced. 

Is there any problem with this?

**Comment by ladnir** [comment]
Also see this for fast Lan performance https://eprint.iacr.org/2022/320

For kkrt, there is a setup that outputs the oprf keys k1,..., km. These are chosen at random by the kkrt protocol. Each can be used once by the receiver. 

In reality it's a bit backwards. For a unique index i, the receiver can choose an oprf input xi. The parties compute

(xi', ki) = oprf(i, xi) 

where the receiver learns xi' and the sender learns ki. In this formulation its a bit more clear why the receiver can use ki only once. Since by calling the oprf, a key is picked at random. The key is not a input but an output of the oprf...

**Comment by Shareong** [comment]
Sorry, I'm confused again. My initial idea was this.

We define an OPRF protocol in which a sender **chooses** a random PRF seed s while the receiver chooses r and learns PRF(s,r).

With this definition, we can construct a simple PSI scheme similar to hash comparison where hash is replaced by OPRF: 

1. S chooses a sk, and completes PRF(sk, si) for all elements of S independently. Then S sends  outputs (hash set_1) to R. 
2. S and R complete OPRF(sk, ri) for all elements of R with same sk, and R gets hash set_2.
3. R finds the intersection between set_1 and set_2.

Therefore, the key of this scheme is to find an efficient OPRF with less traffic and low computational complexity.

**Comment by Shareong** [comment]
Oh. I see, thanks.
